In [ ]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, LabelEncoder

data = {
    "Age": [22, 25, 30, 28, 40, 35, 50, 45, 29, 33],
    "Salary": [25000, 40000, 50000, 42000, 60000, 58000, 72000, 68000, 45000, np.nan],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "Education": ["Bachelor", "Master", "PhD", "High School", "Master", "Bachelor", "PhD", "Master", "Bachelor", "High School"],
    "Experience": [1, 2, 5, np.nan, 10, 8, 15, np.nan, 4, 6] 
}

df = pd.DataFrame(data)
print("Initial Datasett:\n", df, "\n")

#Min-Max Normalization

scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])
print("Min-Max Normalization:\n", df_minmax[["Age", "Salary"]], "\n")

#Z-score Normalization
scaler_std = StandardScaler()
df_zscore = df.copy()
df_zscore[["Age", "Salary"]] = scaler_std.fit_transform(df[["Age", "Salary"]])
print("Z-score Normalization:\n", df_zscore[["Age", "Salary"]], "\n")

#RobustScaler
rs = RobustScaler()
df_Robust = df.copy()
df_Robust[["Age","Salary"]] = rs.fit_transform(df[["Age","Salary"]])
print("Robust Sclaer :\n",df_Robust[["Age","Salary"]],"\n")

# Label Encoding (Ordinal)

le = LabelEncoder()
df["Department"] = le.fit_transform(df['Department'])
print("Label Encoding:\n",df[['Age','Salary','Department']])

df_onehot = pd.get_dummies(df, columns=["Department"])
print("One-Hot Encoded Departments:\n", df_onehot.head(), "\n")

print("Missing Values:\n", df.isnull().sum(), "\n")

# Fill missing values

#df["Experience"].fillna(df["Experience"].mean(), inplace=True)
#df["Salary"].fillna(df["Salary"].mean(), inplace=True)

df_fill_mode = df.copy()
df_fill_mode["Department"].fillna(df_fill_mode["Department"].mode()[0], inplace=True)

df_drop = df.dropna()
print("After Filling with Mean/Mode:\n", df_fill_mean, "\n")
print("Dataset size before:", len(df), "after dropping NA:", len(df_drop), "\n")

#  Aggregation

grouped = df.groupby("Department").agg({"Salary": "mean", "Age": "mean"})
print("Mean Salary & Age by Department:\n", grouped, "\n")

# Pivot Table

pivot = pd.pivot_table(df, values="Salary", index="Education", columns="Department", aggfunc="mean")
print("Pivot Table (Salary by Education & Department):\n", pivot, "\n")

# Binning Age (Equal-width)

df["Age_Bin"] = pd.cut(df["Age"], bins=3, labels=["Young", "Middle-aged", "Old"])
print("Age Binning (Equal-width):\n", df[["Age", "Age_Bin"]], "\n")

#  Binning Salary (Equal-frequency)

df["Salary_Bin"] = pd.qcut(df["Salary"].fillna(df["Salary"].mean()), q=3, labels=["Low", "Medium", "High"])
print("Salary Binning (Equal-frequency):\n", df[["Salary", "Salary_Bin"]], "\n")

Initial Dataset:
    Age   Salary Department    Education  Experience
0   22  25000.0         HR     Bachelor         1.0
1   25  40000.0         IT       Master         2.0
2   30  50000.0    Finance          PhD         5.0
3   28  42000.0         HR  High School         NaN
4   40  60000.0         IT       Master        10.0
5   35  58000.0    Finance     Bachelor         8.0
6   50  72000.0         HR          PhD        15.0
7   45  68000.0    Finance       Master         NaN
8   29  45000.0         IT     Bachelor         4.0
9   33      NaN         HR  High School         6.0

Min-Max Normalization:
         Age    Salary
0  0.000000  0.000000
1  0.107143  0.319149
2  0.285714  0.531915
3  0.214286  0.361702
4  0.642857  0.744681
5  0.464286  0.702128
6  1.000000  1.000000
7  0.821429  0.914894
8  0.250000  0.425532
9  0.392857       NaN

Z-score Normalization:
         Age    Salary
0 -1.382608 -1.859349
1 -1.028093 -0.791213
2 -0.437235 -0.079121
3 -0.673578 -0.648794
4  0.744481  0.632970
5  0.153623  0.490552
6  1.926197  1.487480
7  1.335339  1.202643
8 -0.555407 -0.435167
9 -0.082720       NaN

Robust Sclaer :
         Age    Salary
0 -0.904762 -1.388889
1 -0.619048 -0.555556
2 -0.142857  0.000000
3 -0.333333 -0.444444
4  0.809524  0.555556
5  0.333333  0.444444
6  1.761905  1.222222
7  1.285714  1.000000
8 -0.238095 -0.277778
9  0.142857       NaN

Label Encoding:
    Age   Salary  Department
0   22  25000.0           1
1   25  40000.0           2
2   30  50000.0           0
3   28  42000.0           1
4   40  60000.0           2
5   35  58000.0           0
6   50  72000.0           1
7   45  68000.0           0
8   29  45000.0           2
9   33      NaN           1
One-Hot Encoded Departments:
    Age   Salary    Education  Experience  Department_0  Department_1  \
0   22  25000.0     Bachelor         1.0         False          True
1   25  40000.0       Master         2.0         False         False
2   30  50000.0          PhD         5.0          True         False
3   28  42000.0  High School         NaN         False          True
4   40  60000.0       Master        10.0         False         False

   Department_2
0         False
1          True
2         False
3         False
4          True

Missing Values:
 Age           0
Salary        1
Department    0
Education     0
Experience    2
dtype: int64

After Filling with Mean/Mode:
    Age        Salary  Department    Education  Experience
0   22  25000.000000           1     Bachelor       1.000
1   25  40000.000000           2       Master       2.000
2   30  50000.000000           0          PhD       5.000
3   28  42000.000000           1  High School       6.375
4   40  60000.000000           2       Master      10.000
5   35  58000.000000           0     Bachelor       8.000
6   50  72000.000000           1          PhD      15.000
7   45  68000.000000           0       Master       6.375
8   29  45000.000000           2     Bachelor       4.000
9   33  51111.111111           1  High School       6.000

Dataset size before: 10 after dropping NA: 7

Mean Salary & Age by Department:
                   Salary        Age
Department
0           58666.666667  36.666667
1           46333.333333  33.250000
2           48333.333333  31.333333

Pivot Table (Salary by Education & Department):
 Department         0        1        2
Education
Bachelor     58000.0  25000.0  45000.0
High School      NaN  42000.0      NaN
Master       68000.0      NaN  50000.0
PhD          50000.0  72000.0      NaN

Age Binning (Equal-width):
    Age      Age_Bin
0   22        Young
1   25        Young
2   30        Young
3   28        Young
4   40  Middle-aged
5   35  Middle-aged
6   50          Old
7   45          Old
8   29        Young
9   33  Middle-aged

Salary Binning (Equal-frequency):
     Salary Salary_Bin
0  25000.0        Low
1  40000.0        Low
2  50000.0     Medium
3  42000.0        Low
4  60000.0       High
5  58000.0     Medium
6  72000.0       High
7  68000.0       High
8  45000.0        Low
9      NaN     Medium